# Please see the following page for more information: https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way#configuration

webauthn:
  credential_repository: 'App\Repository\WebAuthnKeyRepository'
  user_repository: 'App\Repository\WebAuthnUserRepository'
  creation_profiles:
    default:
      rp:
        id: '%env(RELYING_PARTY_ID)%'
        name: '%env(RELYING_PARTY_NAME)%'
      authenticator_selection_criteria:
        #attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_NO_PREFERENCE
        #require_resident_key: true
        #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED
        user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED
      extensions:
        credProtect: "userVerificationOptional"
        credProps: true
        largeBlob: true
  request_profiles:
    default:
      rp_id: '%env(RELYING_PARTY_ID)%'

  controllers:
    enabled: true
    creation:
      from_user_account:
        options_path: '/api/register/{user_id}/options'
        result_path: '/api/register/{user_id}'
        user_entity_guesser: App\Guesser\FromQueryParameterIdGuesser
