<?php

/**
 * Returns the import map for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "preload" set to true for any modules that are loaded on the initial
 *     page load to help the browser download them earlier.
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => 'app.js',
    ],
    '@symfony/stimulus-bundle' => [
        'path' => '@symfony/stimulus-bundle/loader.js',
    ],
    '@hotwired/stimulus' => [
        //'url' => 'https://cdn.jsdelivr.net/npm/@hotwired/stimulus@3.2.2/+esm',
        'version' => '3.2.2'
    ],
    'chart.js/auto' => [
        //'url' => 'https://cdn.jsdelivr.net/npm/chart.js@4.4.3/auto/+esm',
        'version' => '4.4.3'
    ],
    'chart.js' => [
        //'url' => 'https://cdn.jsdelivr.net/npm/chart.js@3.9.1/+esm',
        'version' => '3.9.1'
    ],
];
